version: "3.3"
services:
  API_Produccion:
    build: ./
    ports:
      - "4000:80"
    environment:
      SERVER: "sqlserver"
      PORT: 1433
      DATABASE: "AppDbContext"
      USERNAME: "sa"
      PASSWORD: "Produccion123*"
      INTEGRATED_SECURITY: "false"
      TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - ProduccionDB
    links:
      - "ProduccionDB"
  ProduccionDB:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sqlserver"
    environment:
      SA_PASSWORD: "Produccion123*"
      ACCEPT_EULA: "Y"
    volumes:
      - ProduccionData:/var/opt/mssql/data
volumes:
  ProduccionData:
